name: "the_mirror"
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^3.2.0
  animated_text_kit: ^4.2.2
  http: ^0.13.5
  url_launcher: ^6.1.10
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  firebase_database: ^10.1.0
  go_router: ^7.0.0
  smooth_page_indicator: ^1.1.0
  lottie: ^2.3.2
  shared_preferences: ^2.1.0
  flutter_native_splash: ^2.2.19
  image_picker: ^0.8.7+4
  firebase_storage: ^11.1.2
  local_auth: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.12.0"
  flutter_lints: ^2.0.1

flutter:
  assets:
    - assets/images/

  uses-material-design: true

flutter_icons:
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#6750A4"

flutter_native_splash:
  color: "#FFFBFF"
  color_dark: "#1C1B1E"
  image: "assets/icon/splash_light.png"
  image_dark: "assets/icon/splash_dark.png"
  android: true
  ios: true